### PR TITLE
replaced single-shot HTTP requests with RETRY()

### PR DESCRIPTION
**Pull request by jameslamb**
Thanks for for this awesome project!

In this PR, I'd like to propose swapping out calls to `httr::POST()` etc. with `httr::RETRY()`. This will make the package more resilient to transient problems like brief network outages or periods where the service(s) it hits are overwhelmed. In my experience, using retry logic almost always improves the user experience with HTTP clients. `httr::RETRY()` is awesome...it already implements exponential backoff and if you want you can customize things like how many retries it attempts and how long it's willing to wait between retries.

I'm working on https://github.com/chircollab/chircollab20/issues/1 as part of Chicago R Collab, an R 'unconference' in Chicago.

Thanks for your time and consideration.

### CODE REVIEW

**Comment by jameslamb** [comment]
I've rebased this to pick up the changes merged into this project in the time since this pull request was opened.

**Comment by jameslamb** [comment]
I just merged in the latest changes from `master` and fixed merge conflicts.

Are you open to this pull request? If not, I'd be happy to close it.

**Comment by krlmlr** [comment]
The tests are failing, is this a false positive or a limitation of `RETRY()`?

**Comment by gaborcsardi** [comment]
@krlmlr Seems like because there is no GH token in the PR.

**Comment by krlmlr** [comment]
Good catch, will try locally.

**Comment by krlmlr** [comment]
Can't rerun, this seems to be a special token. Do the tests work for you locally?

**Comment by gaborcsardi** [comment]
> Can't rerun, this seems to be a special token. Do the tests work for you locally?

Yes.

**Comment by krlmlr** [comment]
I like the approach. Of course we could do better by reviewing the headers. Merging this will ease the pain of failing GHA tests due to rate limits.

**Comment by krlmlr** [comment]
Maybe we should use `RETRY(quiet = FALSE)` or `RETRY(quiet = .progress)` ?

**Comment by gaborcsardi** [comment]
This feels like a big change for me, and I think it would be better to make it optional and opt-in.

**Comment by krlmlr** [comment]
I'll test-drive it so that we can gain more experience here.

Opt-in won't fix the problems right away, we'd need to change all packages that use it to opt in.

**Comment by gaborcsardi** [comment]
What are the problems that this would fix right away?

**Comment by krlmlr** [comment]
I'm hoping that the functions in remotes that access the GitHub API will wait when the rate limit is exceeded, when they would otherwise fail.

**Comment by gaborcsardi** [comment]
> I'm hoping that the functions in remotes that access the GitHub API will wait when the rate limit is exceeded, when they would otherwise fail.

remotes does not use gh for anything.

**Comment by jameslamb** [comment]
This PR has been open for 20+ months, and hasn't received a new comment in over a year. I'm going to close it and leave it to maintainers to make this change separately if you want.

**Pull request closed without merging**
