### PR TITLE
Explore routes.json

### PR DESCRIPTION
**Pull request by jennybc**
This is more for discussion than merging. Related to #8.

I started to poke around that JSON file you found, documenting the GitHub API.

There are just under 400 endpoints there, broken down into sections.

I've made a table ([visit a rendered version](https://github.com/jennybc/gh/blob/api-description/tests/testthat/routes/routes-table.md)) with one row per endpoint and these columns:

  * section (e.g. "issues")
  * method, url, description
  * params, then broken into url substitution params and other params

Were you already working on this?

I don't understand that node wrapper well enough to tell how they use these routes to produce their tests. For example, I don't see where they give all these parameters values. It seems like they do actually place the requests, because I see evidence of token management.

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Thanks! 

I only looked at it really briefly. The API and test generation is here: https://github.com/mikedeboer/node-github/blob/eef99a4979edd6053b8b9af38b82709c310a4443/lib/generate.js#L41-L85

It looks like they only test one set of options for each endpoint. Which is fair if you have ~400 endpoints.

I am wondering if we should generate the test cases on the fly? This is simpler to implement, but could be a nightmare to debug if sg goes wrong.

**Comment by gaborcsardi** [comment]
I think their tests are just broken....

To make tests work, we would need to include meaningful parameters in the JSON, or rather another companion JSON. :(

**Comment by gaborcsardi** [comment]
But maybe it is not so bad. I created a user and an org for testing:
https://github.com/gh-testing
https://github.com/gh-testing-org

We could just use these and two default repos by default, and add parameters for the endpoints that have extra parameters, in another json file:
```json
"/repos/:owner/:repo/deployments" : {
  "owner": "foo",
  "repo": "bar"
}
```
to override/extend the defaults. 
  
Creating this once seems OK, but I am not yet convinced that it can be maintained easily....

**Comment by jennybc** [comment]
This seems like a important early question: will we think of routes.json from note-github as a dependency? And try to keep it up-to-date with them? Or take it as a one-time information dump to start something over here?

Seems like there has to be:

  * routes.json or equivalent, documenting known endpoints
  * parameters.json, defining default values for parameters found in the endpoints
  * something else that specifies which endpoints we will actually test
    - individually or via criteria, such as GET requests that can be formed only using parameters for which we've set defaults) and any additional info (such as over-riding or augmenting default parameter values)

Maybe we would't rig this up to actually trigger test failure. "Success" could just mean successfully forming some sort of a table like this for human inspection:

  * one row per endpoint
  * one column for
    - formed request
    - placed request
    - processed request
 
and a code for "skipped/not attempted", "passed", "failed" (also incorporating your new mocking approach). It could report a summary and more details on the failures.

Does this sound generally sensible? If so, I will try to make some progress and check back in. Or again, I can step away if you find it easier to do yourself.

**Comment by jennybc** [comment]
Semi-off-topic: Just having routes.json does mean we could generate documentation for all the endpoints within gh. I can't decide if that would be worth it or not though.

**Comment by gaborcsardi** [comment]
I would treat `routes.json` as a dependency, but copy it over. Then we would update it as we please. If we only use it for tests, this is not terribly important, I mean when and how we update.

I think we can test "all" endpoints that we have parameters for. A simple approach is to check if the endpoint is in `test-params.json`. If yes, we generate a test for it. If not, we don't. So we don't have to write all parameters to begin testing.

I think it is not crucial to have `parameters.json`, we don't need it for the tests.

What's wrong with triggering test failures? I think we can do that, there is nothing wrong with it. We don't have to overcomplicate this. :)

I can create a token for the `gh-testing` user and share that with you using `hadley/secure`, then you can actually run the tests. I'll try to get to it today evening.

As for docs, yes, that would be great, `node-github` has very nice auto-generated docs at http://mikedeboer.github.io/node-github/ But this is for later. It would probably make more sense if we auto-generated the API client as well. I have some ideas for that, actually.

**Comment by gaborcsardi** [comment]
It seems unlikely that we would do this in gh any time soon, so I am going to close this. The routes.json files still exists at a different location, and it is updated regularly, so we might do it later, or in another package: https://github.com/octokit/rest.js/blob/master/plugins/rest-api-endpoints/routes.json

**Comment by jennybc** [comment]
Yes, I think it was past time to put this to rest ⚰️🙂

I would be much better at this sort of thing now!

**Pull request closed without merging**
